Simplify config and port setup
moyix/fauxpilot pull request #73
Opened 2022-10-03 12:23 UTC by fdegier

2022-10-03 12:30 UTC, fdegier commented
@moyix @Frederisk this is a follow up from the discussion we had in https://github.com/moyix/fauxpilot/pull/66

I think this PR superseded #66 if it resolved the discussions we still had left.

2022-10-03 21:26 UTC, moyix commented
This looks good to me, but my GPUs are currently occupied on a long-running task so I can't test immediately. Will do so once I have a free GPU and can run a quick smoke test! :)

2022-10-03 21:42 UTC, fdegier commented
@moyix thanks, I tried testing different scenarios but its quite difficult. I tried setting up some automated tests but with my Apple Silicon there is not a lot that I can do due to dependency issues and not having a GPU :D

2022-10-06 17:16 UTC, moyix requested changes
I noticed two issues in setup.sh with this, but otherwise it looks good!

2022-10-19 12:19 UTC, fdegier commented on setup.sh
> +echo "GPUS=${GPUS%?}" >> .env
Thanks for the review! Somewhere the 0 zero got lost in my trial and error to get the comma's. 

Currently in main there is `export GPUS=$(seq 0 $(( NUM_GPUS - 1 )) | paste -sd ',')` which doesn't work which you now solved by adding the `-`. That works, I've added it to a new commit.

2022-10-19 12:53 UTC, fdegier commented on launch.sh
> +docker compose up -d --remove-orphans || docker-compose up -d --remove-orphans
I was having issues with `orphan` containers, as well as the `command -v docker-compose > /dev/null; then` resulting in `docker compose` leading to `docker: 'compose' is not a docker command.`

2022-10-19 16:14 UTC, merged